## cache TTL -- fd
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=2592000" # 2592000 secs = 30 days; 31536000 secs = 365 days; 604800 secs = 7 days
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=2592000"
[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=2592000"
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

## Simple redirects -- fd
[[redirects]]
  from = "/jarrah-timber-decking/"
  to = "/timber-decking/jarrah/"
  status = 301
  force = true # ensure that we always redirect
[[redirects]]
  from = "/timber-wall/trend-plank/"
  to = "/timber-cladding/trend-plank/"
  status = 301
  force = true
[[redirects]]
  from = "/timber-wall/shou-sugi-ban/"
  to = "/timber-cladding/shou-sugi-ban/"
  status = 301
  force = true
[[redirects]]
  from = "/vacoa-cladding/"
  to = "/timber-cladding/vacoa-cladding/"
  status = 301
  force = true
[[redirects]]
  from = "/news/traditional-techniques-inspiring-modern-marvels-shou-sugi-ban/"
  to = "/news/what-is-shou-sugi-ban/"
  status = 301
  force = true
[[redirects]]
  from = "/project/kewdale-toyota/kewdale-toyota-vic-ash-proplank-timber-battens-13/"
  to = "/project/kewdale-toyota/"
  status = 301
  force = true
[[redirects]]
  from = "/2018/09/"
  to = "/"
  status = 301
  force = true
[[redirects]]
  from = "/staging/project/aria-luxury-apartments/img_6447/"
  to = "/project/aria-luxury-apartments/"
  status = 301
  force = true